CREATE DATABASE IS3_CASTELLANOS_RONALDD

CREATE TABLE USUARIO(
    USU_ID SERIAL NOT NULL,
    USU_NOMBRE VARCHAR (50),
    USU_CATALOGO INTEGER,
    USU_PASSWORD VARCHAR (150),
    USU_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (USU_ID)
);

CREATE TABLE OPERACION (
    OP_ID SERIAL NOT NULL,
    OP_NOMBRE VARCHAR (100),
    OP_ESTADO VARCHAR (20),
    OP_FECHA DATETIME YEAR TO MINUTE,
    OP_COMANDO VARCHAR (100),
    OP_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (OP_ID)
);

CREATE TABLE ROL (
    ROL_ID SERIAL NOT NULL,
    ROL_NOMBRE VARCHAR (75),
    ROL_NOMBRE_CT VARCHAR (25),
    ROL_OP INTEGER,
    ROL_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (ROL_ID),
    FOREIGN KEY (ROL_OP) REFERENCES OPERACION (OP_ID)
);